### ISSUE TITLE
Get avatar from discord (beta) returns ssl error

### ISSUE THREAD

**Issue by Dino-log** [anditv21/panel#121]
**To Reproduce**
Steps to reproduce the bug:
Idk i did everything right except for that im not using php 8.0

**Expected behavior**
To get the profile picture from discord

**Screenshots**
![image](https://github.com/anditv21/panel/assets/66836260/433615b7-5e45-4932-9500-e54ea097fa8b)

**Comment by httpete69** [comment]
Hi,
Thanks for reporting the error.

The error in the screenshot indicates that either there is an error with the SSL certificate of your website or you are using http.

But without further context it's not easy to say what the problem is.

If you say that you are not using a current php version, don't be surprised if it doesn't work.

Also neither me nor @anditv21 can help you if you don't give us an error log. This must be clear to you.

**Comment by httpete69** [comment]
![1108064254931783732](https://github.com/anditv21/panel/assets/121981743/d07f9391-9a83-47f2-a0ea-bf925f45b58e)
