### ISSUE TITLE
[Bug]: Undefined constant "PASSWORD_ARGON2I"  and Error: Call to undefined method UserController::flushtokens() 

### ISSUE THREAD

**Issue by trendesetter** [anditv21/panel#162]
### Describe the bug

When changing my password or registering I got this error, the site is on hosting

### Reproduction Steps

When changing the password or registration error occurs, perhaps because php does not support ARGON

### Expected behavior

Correctly change password or register

### Error Log

Fatal error: Uncaught Error: Undefined constant "PASSWORD_ARGON2I" in /var/www/project-orion.pw/data/www/project-orion.pw/app/controllers/UserController.php:303 Stack trace: #0 /var/www/project-orion.pw/data/www/project-orion.pw/user/profile.php(37): UserController->updateUserPass(Array) #1 {main} thrown in /var/www/project-orion.pw/data/www/project-orion.pw/app/controllers/UserController.php on line 303

Fatal error: Uncaught Error: Call to undefined method UserController::flushtokens() in /var/www/project-orion.pw/data/www/project-orion.pw/app/controllers/UserController.php:316 Stack trace: #0 /var/www/project-orion.pw/data/www/project-orion.pw/user/profile.php(37): UserController->updateUserPass(Array) #1 {main} thrown in /var/www/project-orion.pw/data/www/project-orion.pw/app/controllers/UserController.php on line 316

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anditv21** [comment]
Hello trendesetter,
Thanks for your bug report!

I was able to reproduce the error with the password change and have [fixed](https://github.com/anditv21/panel/releases/latest) it.
This probably occurred when I took over the theme from another panel project.

Regarding your error with the registration of users.
Unfortunately I could not reproduce this (Fatal error: Uncaught Error: Undefined constant “PASSWORD_ARGON2I”)

I suspect that you are using an outdated php version 
PHP supports [Argon2](https://wiki.php.net/rfc/argon2_password_hash) since version 7.2. 

You can check this with setup.php.

**Comment by trendesetter** [comment]
I fixed my error “PASSWORD_ARGON2I” by enabling sodium in php settings
